using System;
using System.Diagnostics;
using System.Diagnostics.Tracing;
using System.Text;
using Microsoft.Diagnostics.Tracing;
using Address = System.UInt64;

#pragma warning disable 1591        // disable warnings on XML comments not being present

// This code was automatically generated by the TraceParserGen tool, which converts
// an ETW event manifest into strongly typed C# classes.
namespace Microsoft.Diagnostics.Tracing.Parsers
{
    using Microsoft.Diagnostics.Tracing.Parsers.IIS_IsapiTrace;

    [System.CodeDom.Compiler.GeneratedCode("traceparsergen", "2.0")]
    public sealed class IIS_IsapiTraceTraceEventParser : TraceEventParser 
    {
        public static string ProviderName = "IIS_IsapiTrace";
        public static Guid ProviderGuid = new Guid(unchecked((int) 0xa1c2040e), unchecked((short) 0x8840), unchecked((short) 0x4c31), 0xba, 0x11, 0x98, 0x71, 0x03, 0x1a, 0x19, 0xea);
        public enum Keywords : long
        {
        };

        public IIS_IsapiTraceTraceEventParser(TraceEventSource source) : base(source) {}

        private static Guid W3IsapiTaskGuid = new Guid("{acade3b2-b7d7-4339-956c-811b4edb1b24}");

        public event Action<W3IsapiCALL_ISAPI_EXTENSIONArgs> W3IsapiCALL_ISAPI_EXTENSION
        {
            add
            {
                source.RegisterEventTemplate(W3IsapiCALL_ISAPI_EXTENSIONTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 65535, ProviderGuid);
            }
        }
        public event Action<W3IsapiISAPI_EXTENSION_DONEArgs> W3IsapiISAPI_EXTENSION_DONE
        {
            add
            {
                source.RegisterEventTemplate(W3IsapiISAPI_EXTENSION_DONETemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 65535, ProviderGuid);
            }
        }
        public event Action<W3IsapiNOTIFY_ISAPI_COMPLETIONArgs> W3IsapiNOTIFY_ISAPI_COMPLETION
        {
            add
            {
                source.RegisterEventTemplate(W3IsapiNOTIFY_ISAPI_COMPLETIONTemplate(value));
            }
            remove
            {
                source.UnregisterEventTemplate(value, 65535, ProviderGuid);
            }
        }

        #region private
        protected override string GetProviderName() { return ProviderName; }

        static private W3IsapiCALL_ISAPI_EXTENSIONArgs W3IsapiCALL_ISAPI_EXTENSIONTemplate(Action<W3IsapiCALL_ISAPI_EXTENSIONArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new W3IsapiCALL_ISAPI_EXTENSIONArgs(action, 65535, 1, "W3Isapi", W3IsapiTaskGuid, 11, "CALL_ISAPI_EXTENSION", ProviderGuid, ProviderName );
        }
        static private W3IsapiISAPI_EXTENSION_DONEArgs W3IsapiISAPI_EXTENSION_DONETemplate(Action<W3IsapiISAPI_EXTENSION_DONEArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new W3IsapiISAPI_EXTENSION_DONEArgs(action, 65535, 1, "W3Isapi", W3IsapiTaskGuid, 10, "ISAPI_EXTENSION_DONE", ProviderGuid, ProviderName );
        }
        static private W3IsapiNOTIFY_ISAPI_COMPLETIONArgs W3IsapiNOTIFY_ISAPI_COMPLETIONTemplate(Action<W3IsapiNOTIFY_ISAPI_COMPLETIONArgs> action)
        {                  // action, eventid, taskid, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName
            return new W3IsapiNOTIFY_ISAPI_COMPLETIONArgs(action, 65535, 1, "W3Isapi", W3IsapiTaskGuid, 12, "NOTIFY_ISAPI_COMPLETION", ProviderGuid, ProviderName );
        }

        static private volatile TraceEvent[] s_templates;
        protected override void EnumerateTemplates(Func<string, string, EventFilterResponse> eventsToObserve, Action<TraceEvent> callback)
        {
            if (s_templates == null)
            {
                var templates = new TraceEvent[3];
                templates[0] = W3IsapiISAPI_EXTENSION_DONETemplate(null);
                templates[1] = W3IsapiCALL_ISAPI_EXTENSIONTemplate(null);
                templates[2] = W3IsapiNOTIFY_ISAPI_COMPLETIONTemplate(null);
                s_templates = templates;
            }
            foreach (var template in s_templates)
                if (eventsToObserve == null || eventsToObserve(template.ProviderName, template.EventName) == EventFilterResponse.AcceptEvent)
                    callback(template);
        }

        #endregion
    }
}

namespace Microsoft.Diagnostics.Tracing.Parsers.IIS_IsapiTrace
{
    public sealed class W3IsapiCALL_ISAPI_EXTENSIONArgs : TraceEvent
    {
        public Guid ContextId { get { return GetGuidAt(0); } }
        public string DllName { get { return GetUnicodeStringAt(16); } }

        #region Private
        internal W3IsapiCALL_ISAPI_EXTENSIONArgs(Action<W3IsapiCALL_ISAPI_EXTENSIONArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != SkipUnicodeString(16)));
            Debug.Assert(!(Version > 1 && EventDataLength < SkipUnicodeString(16)));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<W3IsapiCALL_ISAPI_EXTENSIONArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "ContextId", ContextId);
             XmlAttrib(sb, "DllName", DllName);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "ContextId", "DllName"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return ContextId;
                case 1:
                    return DllName;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<W3IsapiCALL_ISAPI_EXTENSIONArgs> m_target;
        #endregion
    }
    public sealed class W3IsapiISAPI_EXTENSION_DONEArgs : TraceEvent
    {
        public Guid ContextId { get { return GetGuidAt(0); } }

        #region Private
        internal W3IsapiISAPI_EXTENSION_DONEArgs(Action<W3IsapiISAPI_EXTENSION_DONEArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != 16));
            Debug.Assert(!(Version > 1 && EventDataLength < 16));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<W3IsapiISAPI_EXTENSION_DONEArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "ContextId", ContextId);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "ContextId"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return ContextId;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<W3IsapiISAPI_EXTENSION_DONEArgs> m_target;
        #endregion
    }
    public sealed class W3IsapiNOTIFY_ISAPI_COMPLETIONArgs : TraceEvent
    {
        public Guid ContextId { get { return GetGuidAt(0); } }

        #region Private
        internal W3IsapiNOTIFY_ISAPI_COMPLETIONArgs(Action<W3IsapiNOTIFY_ISAPI_COMPLETIONArgs> target, int eventID, int task, string taskName, Guid taskGuid, int opcode, string opcodeName, Guid providerGuid, string providerName)
            : base(eventID, task, taskName, taskGuid, opcode, opcodeName, providerGuid, providerName)
        {
            this.m_target = target;
        }
        protected override void Dispatch()
        {
            m_target(this);
        }
        protected override void Validate()
        {
            Debug.Assert(!(Version == 1 && EventDataLength != 16));
            Debug.Assert(!(Version > 1 && EventDataLength < 16));
        }
        protected override Delegate Target
        {
            get { return m_target; }
            set { m_target = (Action<W3IsapiNOTIFY_ISAPI_COMPLETIONArgs>) value; }
        }
        public override StringBuilder ToXml(StringBuilder sb)
        {
             Prefix(sb);
             XmlAttrib(sb, "ContextId", ContextId);
             sb.Append("/>");
             return sb;
        }

        public override string[] PayloadNames
        {
            get
            {
                if (payloadNames == null)
                    payloadNames = new string[] { "ContextId"};
                return payloadNames;
            }
        }

        public override object PayloadValue(int index)
        {
            switch (index)
            {
                case 0:
                    return ContextId;
                default:
                    Debug.Assert(false, "Bad field index");
                    return null;
            }
        }

        private event Action<W3IsapiNOTIFY_ISAPI_COMPLETIONArgs> m_target;
        #endregion
    }
}
